version: '2'
services:
  db:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=paradise
      - MYSQL_PASSWORD=paradise2017
      - MYSQL_DATABASE=ping-pong

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_USER=paradise
      - MYSQL_PASSWORD=paradise2017
      - MYSQL_DATABASE=ping-pong

  game:
    build: ./game
    command: python main.py
    volumes:
      - ./game:/code/game
    ports:
      - "5000:5000"
    environment:
      - API_HOST=api
      - API_PORT=8000

  nginx:
    image: khrall/rpi-nginx
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - game
