# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_1',
            field=models.IntegerField(validators=django.core.validators.MinValueValidator),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_2',
            field=models.IntegerField(validators=django.core.validators.MinValueValidator),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(choices=[(1, 'Player 1'), (2, 'Player 2')]),
        ),
    ]
