# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20170205_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
